# Generated by Django 6.1.1 on 2026-09-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basin_name', models.CharField(max_length=255, verbose_name='Nom du Bassin')),
                ('country', models.CharField(default='Morocco', max_length=50, verbose_name='Pays')),
                ('outlet_lat', models.FloatField(verbose_name='Latitude Exutoire')),
                ('outlet_lon', models.FloatField(verbose_name='Longitude Exutoire')),
                ('area_km2', models.FloatField(verbose_name='Superficie (km²)')),
                ('aridity', models.FloatField(verbose_name="Indice d'Aridité")),
                ('envelope_status', models.CharField(default='valid', max_length=50, verbose_name='Statut Enveloppe')),
                ('verdict_text', models.TextField(blank=True, verbose_name='Verdict')),
                ('kge_monthly', models.FloatField(blank=True, null=True, verbose_name='KGE Mensuel')),
                ('nse_monthly', models.FloatField(blank=True, null=True, verbose_name='NSE Mensuel')),
                ('attributes_json', models.JSONField(default=dict, verbose_name='Attributs Physiques')),
                ('results_json', models.JSONField(default=dict, verbose_name='Résultats Synthétiques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de simulation')),
            ],
            options={
                'verbose_name': 'Simulation Hydrologique',
                'verbose_name_plural': 'Simulations Hydrologiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
